// Configuración FileMaker (opcional)
const FILEMAKER_URL = process.env.FILEMAKER_URL || "";
const FILEMAKER_DATABASE = process.env.FILEMAKER_DATABASE || "";
const FILEMAKER_CREDENTIALS_BASE64 =
  process.env.FILEMAKER_CREDENTIALS_BASE64 || "";
const FILEMAKER_RESULTADOSLAYOUT = process.env.FILEMAKER_RESULTADOSLAYOUT || "";
const FILEMAKER_MEDICOSLAYOUT = process.env.FILEMAKER_MEDICOSLAYOUT || "";
const FILEMAKER_PUBLICACIONESLAYOUT =
  process.env.FILEMAKER_PUBLICACIONESLAYOUT || "";

// Configuración para TheFactoryHKA e-CF API
let THEFACTORY_BASE_URL = "https://demoemision.thefactoryhka.com.do/api";
let THEFACTORY_AUTH_URL = `${THEFACTORY_BASE_URL}/Autenticacion`;
let THEFACTORY_ENVIAR_URL = `${THEFACTORY_BASE_URL}/Enviar`;
let THEFACTORY_ESTATUS_URL = `${THEFACTORY_BASE_URL}/EstatusDocumento`;
let THEFACTORY_EMAIL_URL = `${THEFACTORY_BASE_URL}/EnvioCorreo`;
let THEFACTORY_ANULACION_URL = `${THEFACTORY_BASE_URL}/Anulacion`;
let THEFACTORY_DESCARGA_URL = `${THEFACTORY_BASE_URL}/DescargaArchivo`;
let THEFACTORY_USUARIO = process.env.THEFACTORY_USUARIO;
let THEFACTORY_CLAVE = process.env.THEFACTORY_CLAVE;
let THEFACTORY_RNC = process.env.THEFACTORY_RNC;

module.exports = {
  FILEMAKER_URL,
  FILEMAKER_DATABASE,
  FILEMAKER_CREDENTIALS_BASE64,
  FILEMAKER_RESULTADOSLAYOUT,
  FILEMAKER_MEDICOSLAYOUT,
  FILEMAKER_PUBLICACIONESLAYOUT,
  THEFACTORY_BASE_URL,
  THEFACTORY_AUTH_URL,
  THEFACTORY_ENVIAR_URL,
  THEFACTORY_ESTATUS_URL,
  THEFACTORY_EMAIL_URL,
  THEFACTORY_ANULACION_URL,
  THEFACTORY_DESCARGA_URL,
  THEFACTORY_USUARIO,
  THEFACTORY_CLAVE,
  THEFACTORY_RNC,
};
